apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-cafe-deployment
  namespace: {{ .Values.namespaceName }}
spec:
  replicas: {{ .Values.frontCafe.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontCafe.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontCafe.label }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - front
      containers:
        - name: {{ .Values.frontCafe.containers.name }}
          image: "{{ .Values.frontCafe.containers.image.repository }}:{{ .Values.frontCafe.containers.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontCafe.containers.containerPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontCafe.containers.containerPort }}
            initialDelaySeconds: {{ .Values.frontCafe.containers.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontCafe.containers.periodSeconds }}
            timeoutSeconds: {{ .Values.frontCafe.containers.timeoutSeconds }}
            failureThreshold: {{ .Values.frontCafe.containers.failureThreshold }}
