apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-cafe-ingress
  namespace: {{ .Values.namespaceName }}
spec:
  ingressClassName: nginx
  rules:
    - host: aa0059100549f4ddba101319275ed534-554976623.us-east-1.elb.amazonaws.com/
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-cafe-service
                port:
                  number: 80
