apiVersion: v1
kind: Service
metadata:
  name: front-cafe-service
  namespace: {{ .Values.namespaceName }}
spec:
  selector:
    app: front-cafe
  ports:
    - port: 80
      targetPort: {{ .Values.frontCafe.containerPort }}
  type: ClusterIP
