apiVersion: v1
kind: Service
metadata:
  name: cafe-front-service
  namespace: {{ .Values.namespaceName }}
spec:
  selector:
    app: front-cafe
  ports:
    - port: {{ .Values.frontCafe.containerPort }}
      targetPort: {{ .Values.frontCafe.containerPort }}
  type: LoadBalancer
