apiVersion: v1
kind: Service
metadata:
  name: front-cafe-service
  namespace: {{ .Values.namespaceName }}
spec:
  selector:
    app: {{ .Values.frontCafe.label }}
  ports:
    - port: {{ .Values.frontCafe.containers.containerPort }}
      targetPort: {{ .Values.frontCafe.containers.containerPort }}
  type: ClusterIP
