namespaceName: front-ns

frontCafe:
  replicas: 1
  label: front-cafe
  name: front-cafe-service
  containers:
    name: cafe-front-prod-container
    containerPort: 80
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 10
    image:
      repository: kenu21/cafe-front-prod-image
      tag:
